name: Unit tests
on: [push]
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install gcc and address santiniser
        run:  sudo apt install build-essential libasan6
      - name: compile
        run:  gcc main.c
      - name: run tests
        run: ./test.sh